Vendas.WebApp/Controllers/CargoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Vendas.WebApp.Controllers.Exceptions;
using Vendas.WebApp.Models;
using Vendas.WebApp.Service;
namespace Vendas.WebApp.Controllers
{
    public class CargoController : Controller
    {
        private readonly CargoService _cargoService;
        public CargoController(CargoService cargoService)
        {
            _cargoService = cargoService;
        }

        //Index - Assincrono
        public async Task<IActionResult> Index()
        {
            Session();
            return View(await _cargoService.FindAllAsync());
        }

        //Create - Sincrono
        public IActionResult Create()
        {
            Session();
            return View();
        }

        //Create - Assincrono
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Cargo cargo)
        {
            await _cargoService.InsertAsync(cargo);
            return RedirectToAction(nameof(Index));
        }

        //Details - Assincrono
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var cargo = await _cargoService.FindByIdAsync(id.Value);
            if (cargo == null)
            {
                return NotFound();
            }
            return View(cargo);
        }

        //Delete - Assincrono
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var Cargo = await _cargoService.FindByIdAsync(id.Value);
            if (Cargo == null)
            {
                return NotFound();
            }
            return View(Cargo);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            await _cargoService.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }

        //Edit - Assincrono
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var Cargo = await _cargoService.FindByIdAsync(id.Value);
            if (Cargo == null)
            {
                return NotFound();
            }
            return View(Cargo);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Cargo Cargo)
        {
            if (id != Cargo.Id)
            {
                return BadRequest();
            }
            try
            {
                await _cargoService.Update(Cargo);
                return RedirectToAction(nameof(Index));
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
            catch (DbConcurrencyException)
            {
                return BadRequest();
            }
        }
        public void Session()
        {
            ViewBag.Message = HttpContext.Session.GetString("UserName");
            ViewBag.Message1 = HttpContext.Session.GetString("UserCargo");
        }
    }
}

Vendas.WebApp/Controllers/CompraController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Vendas.WebApp.Service;
namespace Vendas.WebApp.Controllers
{
    public class CompraController : Controller
    {
        private readonly CompraService _CompraService;
        public CompraController(CompraService CompraService)
        {
            _CompraService = CompraService;
        }
        //Index - Sincrono
        public IActionResult Index()
        {
            Session();
            return View(_CompraService.FindAll());
        }
        public void Session()
        {
            ViewBag.Message = HttpContext.Session.GetString("UserName");
            ViewBag.Message1 = HttpContext.Session.GetString("UserCargo");
        }
    }
}

Vendas.WebApp/Controllers/PedidoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Vendas.WebApp.Service;
namespace Vendas.WebApp.Controllers
{
    public class PedidoController : Controller
    {
        private readonly PedidoService _pedidoService;
        public PedidoController(PedidoService pedidoService)
        {
            _pedidoService = pedidoService;
        }
        //Index - Sincrono
        public IActionResult Index()
        {
            Session();
            return View(_pedidoService.FindAll());
        }
        public void Session()
        {
            ViewBag.Message = HttpContext.Session.GetString("UserName");
            ViewBag.Message1 = HttpContext.Session.GetString("UserCargo");
        }
    }
}

Vendas.WebApp/Controllers/VendaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using Vendas.WebApp.Controllers.Exceptions;
using Vendas.WebApp.Models.ViewModels;
using Vendas.WebApp.Service;
namespace Vendas.WebApp.Controllers
{
    public class VendaController : Controller
    {
        private readonly VendaService _vendaService;
        private readonly ComandaService _comandaService;
        public VendaController(VendaService vendaService, ComandaService comandaService)
        {
            _vendaService = vendaService;
            _comandaService = comandaService;
        }
        public async Task<IActionResult> Index()
        {
            Session();
            return View(await _vendaService.FindAllAsync());
        }
        //Create - Assincrono - 1
        public async Task<IActionResult> Create()
        {
            Session();
            var comandas = await _comandaService.FindAllAsync();
            var viewModel = new VendaFormViewModels { Comandas = comandas };
            return View(viewModel);
        }
        //Create - Assincrono - 2
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Vendas.WebApp.Models.Venda venda)
        {
            venda.Data = DateTime.Now.ToString();
            await _vendaService.InsertAsync(venda);
            return RedirectToAction("Create", "VendaProduto", new { VendaId = venda.Id });
        }
        //Details - Assincrono
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var venda = await _vendaService.FindByIdAsync(id.Value);
            if (venda == null)
            {
                return NotFound();
            }
            return View(venda);
        }
        //Delete - Assincrono
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var venda = await _vendaService.FindByIdAsync(id.Value);
            if (venda == null)
            {
                return NotFound();
            }
            return View(venda);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            await _vendaService.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }
        //Edit - Assincrono
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var venda = await _vendaService.FindByIdAsync(id.Value);
            if (venda == null)
            {
                return NotFound();
            }
            return View(venda);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Vendas.WebApp.Models.Venda venda)
        {
            if (id != venda.Id)
            {
                return BadRequest();
            }
            try
            {
                await _vendaService.Update(venda);
                return RedirectToAction(nameof(Index));
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
            catch (DbConcurrencyException)
            {
                return BadRequest();
            }
        }
        public void Session()
        {
            ViewBag.Message = HttpContext.Session.GetString("UserName");
            ViewBag.Message1 = HttpContext.Session.GetString("UserCargo");
        }
    }
}

Vendas.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - FSI - Furlaneti Suporte Informática  </p>
        </footer>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Vendas.WebApp/Views/Shared/_PartialNav.cshtml
<nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a asp-area="" asp-controller="Home" asp-action="Details">Home</a></li>
                @{if (@ViewBag.Message1 == "Gerente")
                    {
                        <li><a asp-area="" asp-controller="Cargo" asp-action="Index">Cargo</a></li>
                        <li><a asp-area="" asp-controller="Categoria" asp-action="Index">Categoria</a></li>
                        <li><a asp-area="" asp-controller="Compra" asp-action="Index">Lista de compra</a></li>
                        <li><a asp-area="" asp-controller="Produto" asp-action="Index">Produto</a></li>
                        <li><a asp-area="" asp-controller="Usuario" asp-action="Index">Usuario</a></li>
                    }
                }
                <li><a asp-area="" asp-controller="Cliente" asp-action="Index">Cliente</a></li>
                <li><a asp-area="" asp-controller="Comanda" asp-action="Index">Comanda</a></li>
                <li><a asp-area="" asp-controller="ComandaProduto" asp-action="Index">Comanda Produto</a></li>
                <li><a asp-area="" asp-controller="Pagamento" asp-action="Index">Pagamento</a></li>
                <li><a asp-area="" asp-controller="Pedido" asp-action="Index">Pedido</a></li>
                <li><a asp-area="" asp-controller="Venda" asp-action="Index">Venda</a></li>
                <li><a><span class="glyphicon glyphicon-user"></span> @ViewBag.Message</a></li>
                <li><a><span class="glyphicon glyphicon-paperclip"></span> @ViewBag.Message1</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="Index"><span class="glyphicon glyphicon-log-out"></span> Sair</a></li>
            </ul>
        </div>
    </div>
</nav>
<input name="UserId" id="UserId" type="hidden" value="@ViewBag.MessageId"/>